---
title: "NEWS"
output: github_document
---

lecat v1.92 (Release date: 2021-04-17)
==============

Changes:

* Added advanced search which allows the specification of custom regex searches.


lecat v1.90 (Release date: 2020-07-26)
==============

Changes:

* Fixed and sped up cotable calculations
* Changed ui for regex
* Added unit test

lecat v1.80 (Release date: 2020-04-19)
==============

Changes:

* Used pkgdown to create site
* Redrafted tutorial section to remove reference to previous YouTube tool
* Rewrote tutorials to package

lecat v1.70 (Release date: 2020-04-17)
==============

Changes:

* Added shiny counter for diagnostic creation
* Simplified code layout for create_cooccurrence_graph function
* Comments added to server.R and ui.R
* Optimised code in run_lecat_analysis.R and create_unique_total_diagnostics. Searches are >50% faster
* Adopted Tidyverse for quicker aggregation of data frames
* Excel files used for input to avoid formatting issues
* Stringr function used for forcing queries and corpus elements to be lower case. Avoids crash when converting some characters found in Tweets
